import {
  BitcoinIcon,
  Blocks,
  Cpu,
  Database,
  Eye,
  FlaskConical,
  Network,
  Package,
  Shield,
  Zap,
} from "lucide-react";
import type { Phase } from "./types";

export const PHASES: Phase[] = [
  {
    id: 0,
    phase: "Phase 0",
    title: "Project Foundation",
    goal: "Bootstrap the monorepo, tooling, and AI development standards.",
    status: "completed",
    completion: 100,
    domain: "core",
    icon: Blocks,
    dateTag: "2025 Q3",
    deliverables: [
      { id: "0.1", label: "Initial monorepo scaffolding (Apps, Packages)", done: true },
      { id: "0.2", label: "Professional Documentation & English Translation", done: true },
      { id: "0.3", label: "Workflow improvements (Concurrent execution, Docker, Scripts)", done: true },
      { id: "0.4", label: "Root configuration (.gitignore, tsconfig.json, docker-compose.yml)", done: true },
      { id: "0.5", label: "AI Development Standards (ai-context.md)", done: true },
    ],
  },
  {
    id: 1,
    phase: "Phase 1",
    title: "Shared Domain & Types",
    goal: "Define the schema and common logic used by both API and Worker.",
    status: "completed",
    completion: 100,
    domain: "core",
    icon: Database,
    dateTag: "2025 Q4",
    deliverables: [
      { id: "1.1.1", label: "Prisma: Core Identity - User, ApiKey, Balance", done: true },
      { id: "1.1.2", label: "Prisma: Financials - TopUp, Order, Escrow, Withdrawal", done: true },
      { id: "1.1.3", label: "Prisma: Details - Milestone, Dispute, AuditLog, IdempotencyKey", done: true },
      { id: "1.1.4", label: "Prisma: Infrastructure - WebhookEvent (deduplication)", done: true },
      { id: "1.1.5", label: "Prisma: Composite indexes for user_id, status, external_id", done: true },
      { id: "1.2.1", label: "Enums: All status enums from state-machines.md", done: true },
      { id: "1.2.2", label: "ID Prefixes: usr_, ord_, topup_, esc_, dsp_, wd_, evt_, aud_", done: true },
      { id: "1.2.3", label: "Error Codes: Full catalog with HTTP mappings", done: true },
      { id: "1.4.1", label: "Prefixed NanoID generator", done: true },
      { id: "1.4.2", label: "Financial arithmetic (Big.js / Decimal.js)", done: true },
      { id: "1.4.3", label: "Amount validator (^\\d+\\.\\d{2}$)", done: true },
      { id: "1.4.4", label: "State machine validator engine (ORDER_TRANSITIONS)", done: true },
    ],
  },
  {
    id: 2,
    phase: "Phase 2",
    title: "Security & Infrastructure",
    goal: "Build the protective shell and the core request handlers.",
    status: "completed",
    completion: 100,
    domain: "core",
    icon: Shield,
    dateTag: "2025 Q4",
    deliverables: [
      { id: "2.1.1", label: "API Key hashing logic (SHA-256 + salt)", done: true },
      { id: "2.1.2", label: "ApiKeyGuard - authenticates ohk_ keys", done: true },
      { id: "2.1.3", label: "ScopeGuard - enforces read, write, support", done: true },
      { id: "2.1.4", label: "Short-lived token logic (ohk_tok_) for frontend use", done: true },
      { id: "2.2.1", label: "IdempotencyGuard: Idempotency-Key header interception", done: true },
      { id: "2.2.2", label: "In-progress locking: prevent concurrent duplicate requests", done: true },
      { id: "2.2.3", label: "Comparison logic: request hash matches stored key body", done: true },
      { id: "2.2.4", label: "TTL Logic: 24h payouts, 7d orders, indefinite disputes", done: true },
      { id: "2.3.1", label: "Global Error Filter: transform to errors.md format", done: true },
      { id: "2.3.2", label: "Standard Response Interceptor: wrap all success responses", done: true },
      { id: "2.3.3", label: "Correlation ID Middleware: X-Request-ID headers", done: true },
      { id: "2.3.4", label: "Global Rate Limiter: Redis-based (100 req/min general)", done: true },
    ],
  },
  {
    id: 3,
    phase: "Phase 3",
    title: "External Providers",
    goal: "Implement the 'Dialects' to talk to external services.",
    status: "completed",
    completion: 100,
    domain: "core",
    icon: Network,
    dateTag: "2026 Q1",
    deliverables: [
      { id: "3.1.1", label: "PaymentProvider interface (Strategy Pattern)", done: true },
      { id: "3.1.2", label: "Crypto-native provider (Stellar wallets, USDC)", done: true },
      { id: "3.1.3", label: "Airtm provider (fiat on/off ramp, optional)", done: true },
      { id: "3.2.1", label: "Stellar wallet logic (Balance projection)", done: true },
      { id: "3.2.2", label: "Escrow contract creation client", done: true },
      { id: "3.2.3", label: "Partial Release / Partial Refund logic", done: true },
      { id: "3.2.4", label: "HMAC Signature verification for TW webhooks", done: true },
    ],
  },
  {
    id: 4,
    phase: "Phase 4",
    title: "Core Services (Business Logic)",
    goal: "The heart of the Orchestrator - State & Money management.",
    status: "completed",
    completion: 100,
    domain: "core",
    icon: Zap,
    dateTag: "2026 Q1",
    deliverables: [
      { id: "4.1.1", label: "Atomic available vs reserved balance updates (Prisma Transactions)", done: true },
      { id: "4.1.2", label: "MIRROR logic: local balance reflects provider state", done: true },
      { id: "4.2.1", label: "Top-Up flow: CREATED -> AWAITING_CONFIRMATION -> PROCESSING -> SUCCEEDED", done: true },
      { id: "4.2.2", label: "Success/Cancel URL redirection and state logic", done: true },
      { id: "4.3.1", label: "Funds reservation (available -= amount, reserved += amount)", done: true },
      { id: "4.3.2", label: "Escrow Bridge: trigger move to Stellar wallet", done: true },
      { id: "4.3.3", label: "Milestones flow: handling partial completions", done: true },
      { id: "4.4.1", label: "Release flow: funds to seller available balance", done: true },
      { id: "4.4.2", label: "Refund flow: funds back to buyer available balance", done: true },
      { id: "4.4.3", label: "Dispute Split: fractional distribution of escrow", done: true },
    ],
  },
  {
    id: 5,
    phase: "Phase 5",
    title: "API Endpoints",
    goal: "Implement every endpoint documented in /docs/api/endpoints.",
    status: "completed",
    completion: 100,
    domain: "core",
    icon: Cpu,
    dateTag: "2026 Q1",
    deliverables: [
      { id: "5.1", label: "Auth & Config Endpoints", done: true },
      { id: "5.2", label: "Users & Balances Endpoints", done: true },
      { id: "5.3", label: "Top-Ups Endpoints", done: true },
      { id: "5.4", label: "Orders & Escrow Endpoints", done: true },
      { id: "5.5", label: "Settlement Endpoints", done: true },
      { id: "5.6", label: "Withdrawals Endpoints", done: true },
    ],
  },
  {
    id: 6,
    phase: "Phase 6",
    title: "Observability",
    goal: "Implement 100% traceability for events and audit.",
    status: "completed",
    completion: 100,
    domain: "core",
    icon: Eye,
    dateTag: "2026 Q1",
    deliverables: [
      { id: "6.1", label: "Internal Event System", done: true },
      { id: "6.2", label: "Real-time SSE (Server-Sent Events)", done: true },
      { id: "6.3", label: "Audit System with full trace logs", done: true },
    ],
  },
  {
    id: 7,
    phase: "Phase 7",
    title: "Background Worker (BullMQ)",
    goal: "Handle asynchronicity, retries, and scheduled health.",
    status: "completed",
    completion: 100,
    domain: "core",
    icon: Cpu,
    dateTag: "2026 Q1",
    deliverables: [
      { id: "7.1", label: "Infrastructure: BullMQ setup, Redis queues, processors", done: true },
      { id: "7.2", label: "Webhook Processing: HMAC verification, deduplication, retry", done: true },
      { id: "7.3", label: "Scheduled Jobs: Reconciliation & Monitoring health checks", done: true },
    ],
  },
  {
    id: 8,
    phase: "Phase 8",
    title: "SDK & Developer Experience",
    goal: "Provide the 'Magic' toolkit for marketplace developers.",
    status: "completed",
    completion: 100,
    domain: "sdk",
    icon: Package,
    dateTag: "2026 Q1",
    deliverables: [
      { id: "8.1.1", label: "@offerhub/sdk: Base Ky-powered client with retry logic", done: true },
      { id: "8.1.2", label: "SDK: Resource mapping (Users, Orders, TopUps, Balance, Disputes)", done: true },
      { id: "8.1.3", label: "SDK: Error typing - InsufficientFundsError, instance checking", done: true },
      { id: "8.1.4", label: "SDK: Idempotency support via withIdempotencyKey()", done: true },
      { id: "8.1.5", label: "SDK: Full TypeScript types & comprehensive documentation", done: true },
      { id: "8.1.6", label: "SDK: Publishing guide for NPM release", done: true },
      { id: "8.2.1", label: "CLI: offerhub keys create/list/revoke", done: true },
      { id: "8.2.2", label: "CLI: offerhub maintenance enable/disable/status", done: true },
      { id: "8.2.3", label: "CLI: offerhub health check command", done: true },
      { id: "8.2.4", label: "CLI: Interactive configuration setup wizard", done: true },
    ],
  },
  {
    id: 9,
    phase: "Phase 9",
    title: "Final Polish & QA",
    goal: "Production readiness, deployment guide, and installer script.",
    status: "in-progress",
    completion: 60,
    domain: "qa",
    icon: FlaskConical,
    dateTag: "2026 Q2",
    deliverables: [
      { id: "9.1", label: "Comprehensive E2E test suite (API -> DB -> Worker)", done: true },
      { id: "9.2", label: "Rate limiting implementation (Redis-based, configurable)", done: true },
      { id: "9.3", label: "Production deployment guide (updated for crypto-native)", done: false },
      { id: "9.4", label: "Installer script: npm create offer-hub-orchestrator@latest", done: false },
      { id: "9.5", label: "Production deployment guide finalized (docs/deployment/)", done: true },
    ],
  },
  {
    id: 10,
    phase: "Phase 10",
    title: "Crypto-Native Provider",
    goal: "Add crypto-native payments via invisible Stellar wallets and USDC.",
    status: "completed",
    completion: 100,
    domain: "crypto",
    icon: BitcoinIcon,
    dateTag: "2026-02-16",
    deliverables: [
      { id: "10.1.1", label: "PaymentProvider interface (Strategy Pattern)", done: true },
      { id: "10.1.2", label: "CryptoNativeProvider implementing the interface", done: true },
      { id: "10.1.3", label: "AES-256-GCM crypto utilities for wallet encryption", done: true },
      { id: "10.1.4", label: "Database migration: new Wallet table", done: true },
      { id: "10.1.5", label: "Env vars: PAYMENT_PROVIDER, WALLET_ENCRYPTION_KEY", done: true },
      { id: "10.2.1", label: "WalletService implementation", done: true },
      { id: "10.2.2", label: "WalletController implementation", done: true },
      { id: "10.2.3", label: "BlockchainMonitorService for real-time deposit detection", done: true },
      { id: "10.2.4", label: "USDC trustline setup for new accounts", done: true },
      { id: "10.3.1", label: "UsersService: auto-create wallet on registration", done: true },
      { id: "10.3.2", label: "BalanceService: sync from blockchain state", done: true },
      { id: "10.3.3", label: "OrdersService: escrow funding via crypto wallet", done: true },
      { id: "10.3.4", label: "ResolutionService: crediting on release/refund", done: true },
      { id: "10.3.5", label: "Update reconciliation jobs for blockchain hashes", done: true },
      { id: "10.4.1", label: "SDK: wallet resource added to @offerhub/sdk", done: true },
      { id: "10.4.2", label: "SDK types updated for crypto-native flows", done: true },
      { id: "10.4.3", label: "CLI installer updated for crypto-native setup", done: true },
      { id: "10.4.4", label: "Deployment docs updated for Stellar/USDC config", done: true },
      { id: "10.4.5", label: "Unit + integration tests for crypto paths", done: true },
      { id: "10.4.6", label: "Testnet E2E verification completed", done: true },
    ],
  },
];
